# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    avatars_upload: '%kernel.project_dir%/public/avatars'
    app_base_url: '%env(APP_BASE_URL)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    App\Command\CreateDefaultRoles:
        tags: ['console.command']

    App\Command\AddTipTopCompany:
        tags: ['console.command']
    
    App\Command\AddPrizesCommand:
        tags: ['console.command']

    App\Command\AddFirstAdmin:
        tags: ['console.command']
    
    App\Command\GenerateDefaultTickets:
        tags: ['console.command']


    App\Command\GenerateFakeData:
        tags: [ 'console.command' ]

    App\Command\GenerateEmailServices:
        tags: [ 'console.command' ]

    App\Command\GenerateEmailTemplatesVariables:
        tags: [ 'console.command' ]

    App\Command\GenerateBadges:
        tags: [ 'console.command' ]

    App\Command\ResetGame:
        tags: [ 'console.command' ]

    App\Service\Mailer\PostManMailerService:
        arguments:
            $mailtrapHost: '%env(MAILTRAP_HOST)%'
            $mailtrapUser: '%env(MAILTRAP_USER)%'
            $mailtrapPassword: '%env(MAILTRAP_PASSWORD)%'
            $mailtrapPort: '%env(MAILTRAP_PORT)%'



