vich_uploader:
    db_driver: orm
    storage: file_system
    mappings:
      avatar:
        namer: Vich\UploaderBundle\Naming\OrignameNamer
        uri_prefix: /avatars
        upload_destination: '%kernel.project_dir%/public/avatars'
